version: "3.0"

services:
  performancemysql:
    build:
      context: './mysql'
    image: performance/mysql:latest
    container_name: performancemysql
    hostname: performancemysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'teste'
    networks:
      dcperformance:
        aliases:
          - performancemysql

  performanceserver:
    build:
      context: './server'
    image: performance/server:latest
    container_name: performanceserver
    hostname: performanceserver
    environment:
      BALANCED: 'true'
    depends_on:
      - performancemysql
    links:
      - performancemysql
    networks:
      dcperformance:
        aliases:
          - performanceserver
    volumes:
      - ../PerformanceServer/target:/opt/performance

  performanceserver2:
    build:
      context: './server'
    image: performance/server:latest
    container_name: performanceserver2
    hostname: performanceserver2
    environment:
      BALANCED: 'true'
    depends_on:
      - performancemysql
    links:
      - performancemysql
    networks:
      dcperformance:
        aliases:
          - performanceserver2
    volumes:
      - ../PerformanceServer/target:/opt/performance

  performancerest:
    build:
      context: './rest'
    image: performance/rest:latest
    container_name: performancerest
    hostname: performancerest
    environment:
      BALANCED: 'true'
    depends_on:
      - performanceserver
      - performanceserver2
    links:
      - performanceserver
      - performanceserver2
    networks:
      dcperformance:
        aliases:
          - performancerest
    volumes:
      - ../PerformanceRest/target:/opt/performance

  performancerest2:
    build:
      context: './rest'
    image: performance/rest:latest
    container_name: performancerest2
    hostname: performancerest2
    environment:
      BALANCED: 'true'
    depends_on:
      - performanceserver
      - performanceserver2
    links:
      - performanceserver
      - performanceserver2
    networks:
      dcperformance:
        aliases:
          - performancerest2
    volumes:
      - ../PerformanceRest/target:/opt/performance

  performancermi:
    build:
      context: './rmi'
    image: performance/rmi:latest
    container_name: performancermi
    hostname: performancermi
    environment:
      BALANCED: 'true'
    depends_on:
      - performanceserver
      - performanceserver2
    links:
      - performanceserver
      - performanceserver2
    networks:
      dcperformance:
        aliases:
          - performancermi
    volumes:
      - ../PerformanceRMI/target:/opt/performance

  performancermi2:
    build:
      context: './rmi'
    image: performance/rmi:latest
    container_name: performancermi2
    hostname: performancermi2
    environment:
      BALANCED: 'true'
    depends_on:
      - performanceserver
      - performanceserver2
    links:
      - performanceserver
      - performanceserver2
    networks:
      dcperformance:
        aliases:
          - performancermi2
    volumes:
      - ../PerformanceRMI/target:/opt/performance

  performancejms:
    build:
      context: './jms'
    image: performance/jms:latest
    container_name: performancejms
    hostname: performancejms
    environment:
      BALANCED: 'true'
    depends_on:
      - performanceserver
      - performanceserver2
    links:
      - performanceserver
      - performanceserver2
    networks:
      dcperformance:
        aliases:
          - performancejms
    volumes:
      - ../PerformanceJMS/target:/opt/performance

  performancejms2:
    build:
      context: './jms'
    image: performance/jms:latest
    container_name: performancejms2
    hostname: performancejms2
    environment:
      BALANCED: 'true'
    depends_on:
      - performanceserver
      - performanceserver2
    links:
      - performanceserver
      - performanceserver2
    networks:
      dcperformance:
        aliases:
          - performancejms2
    volumes:
      - ../PerformanceJMS/target:/opt/performance

  performancehalb:
    build:
      context: './haproxylb'
    image: performance/haproxylb:latest
    container_name: performancehalb
    hostname: performancehalb
    links:
      - performancermi
      - performancermi2
      - performancejms
      - performancejms2
      - performanceserver
      - performanceserver2
      - performancerest
      - performancerest2
    ports:
      - "8080:8080"
    networks:
      dcperformance:
        aliases:
          - performancehalb
    depends_on:
      - performancermi
      - performancermi2
      - performancejms
      - performancejms2
      - performanceserver
      - performanceserver2
      - performancerest
      - performancerest2

networks:
  dcperformance:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
