version: "3.0"

services:
  PerformanceMysql:
    build:
      context: './mysql'
    image: performance/mysql:latest
    container_name: PerformanceMysql
    hostname: performancemysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'teste'
    networks:
      dcperformance:
        aliases:
          - PerformanceMysql

  PerformanceServer:
    build:
      context: './server'
    image: performance/server:latest
    container_name: PerformanceServer
    hostname: performanceserver
    depends_on:
      - PerformanceMysql
    links:
      - PerformanceMysql
    networks:
      dcperformance:
        aliases:
          - PerformanceServer
    volumes:
      - ../PerformanceServer/target:/opt/performance

  PerformanceRest:
    build:
      context: './rest'
    image: performance/rest:latest
    container_name: PerformanceRest
    hostname: performancerest
    depends_on:
      - PerformanceServer
    links:
      - PerformanceServer
    networks:
      dcperformance:
        aliases:
          - PerformanceRest
    volumes:
      - ../PerformanceRest/target:/opt/performance

  PerformanceRMI:
    build:
      context: './rmi'
    image: performance/rmi:latest
    container_name: PerformanceRMI
    hostname: performancermi
    depends_on:
      - PerformanceServer
    links:
      - PerformanceServer
    networks:
      dcperformance:
        aliases:
          - PerformanceRMI
    volumes:
      - ../PerformanceRMI/target:/opt/performance

  PerformanceHA:
    build:
      context: './haproxy'
    image: performance/haproxy:latest
    container_name: PerformanceHA
    hostname: performanceha
    links:
      - PerformanceRMI
      - PerformanceServer
      - PerformanceRest
    ports:
      - "8080:8080"
    networks:
      dcperformance:
        aliases:
          - PerformanceHA
    depends_on:
      - PerformanceRMI
      - PerformanceServer
      - PerformanceRest

networks:
  dcperformance:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
