version: "3.0"

services:
  sessionmysql:
    build:
      context: './mysql'
    image: session/mysql:latest
    container_name: sessionmysql
    hostname: sessionmysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'teste'
    networks:
      dcsession:
        aliases:
          - sessionmysql

  sessioninfinispan:
    build:
      context: './infinispan'
    image: session/infinispan:latest
    container_name: sessioninfinispan
    hostname: sessioninfinispan
    networks:
      dcsession:
        aliases:
          - sessioninfinispan

  sessionejbserver:
    build:
      context: './serverejb'
    image: session/ejbserver:latest
    container_name: sessionejbserver
    hostname: sessionejbserver
    depends_on:
      - sessionmysql
    links:
      - sessionmysql
    networks:
      dcsession:
        aliases:
          - sessionejbserver
    volumes:
      - ../SessionEJBServer/target:/opt/session

  sessionserver:
    build:
      context: './server'
    image: session/server:latest
    container_name: sessionserver
    hostname: sessionserver
    depends_on:
      - sessionmysql
    links:
      - sessionmysql
    networks:
      dcsession:
        aliases:
          - sessionserver
    volumes:
      - ../SessionServer/target:/opt/session

  sessionserver11:
    build:
      context: './servercache'
    image: session/server11:latest
    container_name: sessionserver11
    hostname: sessionserver11
    depends_on:
      - sessionmysql
      - sessioninfinispan
      - sessionejbserver
    links:
      - sessionmysql
      - sessioninfinispan
      - sessionejbserver
    networks:
      dcsession:
        aliases:
          - sessionserver11
    volumes:
      - ../SessionServerCache/target:/opt/server

  sessionserver12:
    build:
      context: './servercache'
    image: session/server12:latest
    container_name: sessionserver12
    hostname: sessionserver12
    depends_on:
      - sessionmysql
      - sessioninfinispan
      - sessionejbserver
    links:
      - sessionmysql
      - sessioninfinispan
      - sessionejbserver
    networks:
      dcsession:
        aliases:
          - sessionserver12
    volumes:
      - ../SessionServerCache/target:/opt/server

  sessionserverjwt1:
    build:
      context: './serverjwt'
    image: session/serverjwt:latest
    container_name: sessionserverjwt1
    hostname: sessionserverjwt1
    depends_on:
      - sessionmysql
    links:
      - sessionmysql
    networks:
      dcsession:
        aliases:
          - sessionserverjwt1
    volumes:
      - ../SessionServerJWT/target:/opt/server

  sessionserverjwt2:
    build:
      context: './serverjwt'
    image: session/serverjwt:latest
    container_name: sessionserverjwt2
    hostname: sessionserverjwt2
    depends_on:
      - sessionmysql
    links:
      - sessionmysql
    networks:
      dcsession:
        aliases:
          - sessionserverjwt2
    volumes:
      - ../SessionServerJWT/target:/opt/server

  sessionha:
    build:
      context: './haproxy'
    image: session/haproxy:latest
    container_name: sessionha
    hostname: sessionha
    links:
      - sessionserver
      - sessionserver11
      - sessionserver12
      - sessionserverjwt1
      - sessionserverjwt2
    ports:
      - "8080:8080"
    networks:
      dcsession:
        aliases:
          - sessionha
    depends_on:
      - sessionserver
      - sessionserver11
      - sessionserver12
      - sessionserverjwt1
      - sessionserverjwt2

networks:
  dcsession:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
