FROM java:8-jdk

MAINTAINER Vanei
LABEL description="Servidor Performance" version="8"

EXPOSE 8080

WORKDIR /opt/performance
#CMD ["java", "-jar", "/opt/performance/PerformanceServer-swarm.jar"]
CMD ["java", "-jar", "PerformanceServer-swarm.jar"]
#CMD ["java", "-jar", "PerformanceServer-swarm.jar", "> server.log"]
#CMD ["java -jar PerformanceServer-swarm.jar > server.log"]
